name: CI/CD Deployment to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GKE_CLUSTER: "my-cluster"
    GKE_REGION: "europe-west3"
    DEPLOYMENT_NAME: "mlops-app"
    REPOSITORY: "europe-west3-docker.pkg.dev/white-byway-467013-f8/iscalo-repo"
    IMAGE: "europe-west3-docker.pkg.dev/white-byway-467013-f8/iscalo-repo/mlops-app"
    USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        #container:
         #   image: google/cloud-sdk:latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Authenticate with Google cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}


            - name: Setup gcloud with GKE auth plugin
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                install_components: 'gke-gcloud-auth-plugin'

            - name: Configure GCloud
              run: |
                gcloud config set project $PROJECT_ID
                gcloud auth configure-docker europe-west3-docker.pkg.dev
            
            - name: Building and Pushing Image
              run: |
                docker build -t $IMAGE:$GITHUB_SHA .
                docker push $IMAGE:$GITHUB_SHA

            - name: GKE Configuration
              run: |
                gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Deploying to Kubernetes
              run: |
                kubectl apply -f kubernetes-deployment.yaml
                kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA
            
            



